### ISSUE TITLE
Support specify a directory instead of  a single file which the argument is `-f` when generate models

### ISSUE THREAD

**Issue by LeoLiuYan** [kcl-lang/kcl-openapi#21]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**
When generate KCL models,  we expect to use a directory argument that all source OpenAPI files in it.
And the command of `kcl-openapi generate model` should scan all files in the directory.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Peefy** [comment]
Supported in the KCL new cli `kcl import` command. Ref: https://github.com/kcl-lang/cli/blob/main/pkg/options/import.go#L38
