### ISSUE TITLE
go struct to kcl schema

### ISSUE THREAD

**Issue by howieyuen** [kcl-lang/kcl-openapi#28]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I am trying to convert Prometheus API to KCL, use `--crd` flag, but I go obscure schema definition like below:

```
schema MonitoringCoreosComV1PodMonitorSpecPodMetricsEndpointsItems0Authorization:
    """ Authorization section for this endpoint

    Attributes
    ----------
    credentials : MonitoringCoreosComV1PodMonitorSpecPodMetricsEndpointsItems0AuthorizationCredentials, default is Undefined, optional
        credentials
    $type : str, default is Undefined, optional
         Set the authentication type. Defaults to Bearer, Basic will cause an error
    """


    credentials?: MonitoringCoreosComV1PodMonitorSpecPodMetricsEndpointsItems0AuthorizationCredentials

    $type?: str
```

schema name is longer than my screen....

Detail: https://github.com/KusionStack/konfig/pull/43/files#diff-113bb68b56de1693d4d7a822059831a84cae205e47f0be2c4aeaeab93e01248cL152

**Describe the feature you'd like:**

Maybe like kubebuilder, we can use go struct, directly generate kcl schemas.

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

None

**Comment by amyXia1994** [comment]
belongs to #33
