### ISSUE TITLE
CRD convert error: no openapi schema found

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kcl-openapi#31]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. unzip the following file and put it in <dir>/oam.yaml

[oam.yaml.zip](https://github.com/KusionStack/kcl-openapi/files/10389714/oam.yaml.zip)

2. run `kcl-openapi generate model --crd --skip-validation -f Desktop/oam.yaml`

### 2. What did you expect to see? (Required)

KCL files generated

### 3. What did you see instead (Required)

error:

```
could not generate swagger spec: Desktop/oam.yaml, err: no openapi schema found in the crd file. Please check following fields: spec.Validation.OpenAPIV3Schema, spec.Versions.0.Schema
```

**Comment by prahaladramji** [comment]
This bug also extends to CRD from spec V1. It also seems to be that [this condition](https://github.com/kcl-lang/kcl-openapi/blob/a2418abc729adb493ae86550b70a25317fe84202/pkg/kube_resource/generator/generator.go#L125) is triggered for all CRD model generation.

eg. crd for [external-secrets operator](https://raw.githubusercontent.com/external-secrets/external-secrets/main/config/crds/bases/external-secrets.io_externalsecrets.yaml)
```bash
kcl-openapi generate model --crd \
  -f <(curl -sS "https://raw.githubusercontent.com/external-secrets/external-secrets/main/config/crds/bases/external-secrets.io_externalsecrets.yaml") \
  --skip-validation

could not generate swagger spec: /dev/fd/11, err: no openapi schema found in the crd file. Please check following fields: spec.Validation.OpenAPIV3Schema, spec.Versions.0.Schema
```
