### ISSUE TITLE
Enhance guide introducing scenarios and solutions around kcl-openapi usage

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kcl-openapi#32]
## Enhancement

the current [guide](https://kusionstack.io/docs/user_docs/guides/adopting/from_kubernetes) now is too Long and obscure, not user friendly

Need to introduce more about scenarios and solutions(k8s and other infra resource migration), and use a demo to tell a story about how to accomplish the goal via kusion(more specifically, kcl-openapi tools)

**Comment by Peefy** [comment]
Enhanced in https://kcl-lang.io/docs/user_docs/guides/working-with-k8s/adopt-from-kubernetes
