### ISSUE TITLE
more code-gen features: From TF/GPL

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kcl-openapi#33]
## Feature Request

More code-gen features are required for the "Adopting From X" series.

- adopting from Terraform(TF provider/HCL)
- adopting from Go/Java/...
- from the perspective of adopting from multiple cloud providers: adopting from k8s/AWS/aliyun

ref:
- pulumi from tf: https://www.pulumi.com/blog/from-terraform-to-infrastructure-as-software/
- tfgen from pulumi: https://github.com/pulumi/pulumi-terraform-bridge
- https://github.com/pulumi/pulumi-aws
- https://github.com/pulumi/pulumi-azure
- https://github.com/pulumi/pulumi-gcp
- https://github.com/pulumi/pulumi-alicloud

<!-- 
从AWS CDK 到 Pulumi：https://ata.alibaba-inc.com/articles/154276?spm=ata.23639746.0.0.357c3566yBIkTN
>

**Comment by Peefy** [comment]
Is it possible to directly support the conversion of jsonschema to KCL or integrate jsonschema in the IDE? For example, Github's workflow and OPA/Rego languages directly integrate jsonschema for validation. Some users have raised similar requirements.

More documents:

+ https://json.schemastore.org/github-workflow.json
+ https://www.openpolicyagent.org/docs/latest/schemas/
