### ISSUE TITLE
Where is the release kcl package for k8s v1.28

### ISSUE THREAD

**Issue by liangyuanpeng** [kcl-lang/kcl-openapi#62]
## General Question

kubernetes v1.28 is release and kcl have not package for k8s 1.28 : https://github.com/orgs/kcl-lang/packages/container/package/k8s

I have got the nothing after checked the doc https://kcl-lang.io/docs/user_docs/guides/working-with-k8s/adopt-from-kubernetes , i have not find the github action for release it, If not I'd like to work on this and would love some guidance, thanks.

I'm not sure is it the right place for this question, if not true and give some guide please,Thanks.

**Comment by i-zhen** [comment]
Hi liangyuanpeng,

You got the right place of guidance to generate the package: https://kcl-lang.io/docs/user_docs/guides/working-with-k8s/adopt-from-kubernetes/#321-get-the-k8s-package 
Maybe it is inconspicuous,  you're encouraged to provide some advice for such doc.

On the other hand, please also refer to: https://github.com/kcl-lang/kcl-openapi/blob/main/docs/generate_from_k8s_spec.md
That will provide more details of generating.

**Comment by liangyuanpeng** [comment]
>  publish the v1.28 package to KCL official repo

Thanks for your quickly reply and that's what i want,  So now is the complete way to work for  release of k8s package?

**Comment by i-zhen** [comment]
> >  publish the v1.28 package to KCL official repo
> 
> 
> 
> Thanks for your quickly reply and that's what i want,  So now is the offline way to complete for  release of k8s package?

Hi, I wonder is it urgent for you? if yes, we will upload a v1.28 officially ASAP.

If no, we will release an official way for you to publish the package in October.
